spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/train_trip
    username: user
    password: user
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update  # 개발 중엔 update / 운영 전환 시에는 validate 또는 none 추천
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MariaDBDialect

  thymeleaf:
    cache: false  # 개발 중엔 false, 배포는 true
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    mode: HTML

    #파일 업로드 설정
  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 20MB

#이미지 업로드 경로 설정
file:
  # 이미지 저장 경로
  upload-dir: src/main/resources/static/uploads/images
  # 웹 접근 경로 (추가 - 오류 해결을 위해)
  upload-path: /uploads/images

  mvc:
    static-path-pattern: /**
  web:
    resources:
      static-locations: classpath:/static/
      cache:
        period: 3600

  security:
    user:
      name: admin
      password: admin  # Spring Security 기본 계정

server:
  port: 8080

logging:
  level:
    org.hibernate.SQL: debug
    org.springframework.security: debug
